#+TITLE: UI3.0 Template
#+Author: VLEAD
#+Date: [2015-09-29 Fri]
#+PROPERTY: session *scratch*
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: org-templates/level-0.org
#+options: ^:nil

* Glossary
** UI1.0 Structure
   This template is to standardize the formats of all labs according
   to the homogeneous hosting framework. It helps you achieve the following:

- *Coding standards:* The template ensures that lab developers follow
  good programming practices to make the code of the labs efficient
  and readable.
- *Upgrading widgets and components:* The template makes it easy for
  lab developers to modify and update widgets and/or components.
- *Unified look and feel:* The UI 1.0 template offers a uniform user
  interface for authoring and interacting with the virtual labs. It
  also provides labs a simple and uniform web interface and a
  homogeneous hosting framework.
- *Provision for better versions of template:* In future, if advanced
  versions of the UI template are created, the lab developers can
  transfer the lab content automatically as per the new versions.
** UI3.0 Structure
   Has to be updated by Sonali

** Amritha Structure  
** Unstructured 
* Introduction
  
* Requirements
* Design
* Implementation
* Test Cases
* Releases
